<a href="https://colab.research.google.com/github/nagoyann9/Study_log_of_Google_Collabolatory/blob/main/Sololearn_DS_with_Python_Data_Manipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Welcome to Data Science
###Why Python?
エンジニアリング環境で他のフレームワーク（Webアプリケーションなど）とうまく統合できます。探索的データ分析の手法を本コースでは利用します。

#Numpy (Numerical:数値の Python) 
Numpyを使用すると、188cmより背が高い大統領の数に対する答えを簡単に見つけることができます。

```
import numpy as np
```
 
importステートメントを使用すると、numpyライブラリ内の関数とモジュールにアクセスできます。 ライブラリは頻繁に使用されるため、慣例により、numpyは短い名前npでインポートされます。

```
heights = [189, 170, 189, 163, 183, 171, 185, 168, 173, 183, 173, 173, 175, 178, 183, 193, 178, 173, 174, 183, 183, 180, 168, 180, 170, 178, 182, 180, 183, 178, 182, 188, 175, 179, 183, 193, 182, 183, 177, 185, 188, 188, 182, 185, 191]
heights_arr = np.array(heights)
```

2行目は、np.array（）を介して、リストをnumpy配列オブジェクトに変換します。このオブジェクトはnumpyで提供されるツールで使用できます。
```
print((heights_arr > 188).sum())
```
データセットが大きく複雑になるにつれて、numpyを使用すると、より効率的でforループのない方法を使用してデータを操作および分析できます。

#pandas
データの統計量を表示したり、グラフ化するなど、データ分析（データサイエンス）のライブラリ

#matplotlib
matplotlibとはPythonにおけるグラフ描画の標準的なライブラリ。様々な種類のグラフを作成する事が出来、使い方を一度覚えておくととても便利。

#scikit-learn
「サイキット・ラーン」と読む。scikit-learnは、現在も活発に開発が行われており、インターネット上で情報を探すのも容易。多くの機械学習アルゴリズムが実装されており、どのアルゴリズムでも同じような書き方で利用することができる。また、サンプルのデータセット（トイデータセット）が付属しており、インストールしてすぐ機械学習を試すことができる。

##できることの例
線形回帰を使用して家の価値を予測し、分類アルゴリズムを使用して虹彩のクラスを識別し、ワイン内のクラスターを見つけます。これは、データサイエンスでできることのほんの一例です。

#数値データ
データセットの形式
データセットは、さまざまなソースと形式から取得されます。数値測定値のコレクション、テキストコーパス、画像、オーディオクリップ、または基本的には何でもかまいません。
データサイエンスの最初のステップ
形式に関係なく、データサイエンスの最初のステップは、データサイエンスを数値の配列に変換することです。

# Size and Shape


An array class in Numpy is called an ndarray or n-dimensional array. We can use this to count the number of presidents in heights_arr, use attribute numpy.ndarray.size



In [6]:
import numpy as np

heights = [189, 170, 189, 163, 183, 171, 185, 168, 173, 183, 173, 173, 175, 178, 183, 193, 178, 173, 174, 183, 183, 180, 168, 180, 170, 178, 182, 180, 183, 178, 182, 188, 175, 179, 183, 193, 182, 183, 177, 185, 188, 188, 182, 185, 191]

heights_arr = np.array(heights)
print(heights_arr.size)

45


Note that once an array is created in numpy, **its size cannot be changed**.

**Size** tells us **how big the array** is, **shape** tells us the **dimension**. To get current shape of an array use attribute shape:

In [8]:
print(heights_arr.size)
print(heights_arr.shape)

45
(45,)


Shape's output is a **tuple**, recall that the built-in data type tuple is immutable whereas a list is mutable, containing a single value, indicating that there is only one dimension, i.e., axis 0. Along axis 0, there are 45 elements (one for each president) Here, heights_arr is a 1d array.

In [9]:
#age of Presidents
ages = [57, 61, 57, 57, 58, 57, 61, 54, 68, 51, 49, 64, 50, 48, 65, 52, 56, 46, 54, 49, 51, 47, 55, 55, 54, 42, 51, 56, 55, 51, 54, 51, 60, 62, 43, 55, 56, 61, 52, 69, 64, 46, 54, 47, 70]

Since both heights and ages are all about the same presidents, we can combine them:

In [10]:
heights_and_ages = heights + ages 
# convert a list to a numpy array
heights_and_ages_arr = np.array(heights_and_ages)
print(heights_and_ages_arr.shape)

(90,)


This produces one long array. It would be clearer if we could align height and age for each president and reorganize the data into a 2 by 45 matrix where the first row contains all heights and the second row contains ages. To achieve this, a new array can be created by calling **numpy.ndarray.reshape** with new dimensions specified in a tuple:


In [11]:
heights_and_ages_arr.reshape((2,45))

array([[189, 170, 189, 163, 183, 171, 185, 168, 173, 183, 173, 173, 175,
        178, 183, 193, 178, 173, 174, 183, 183, 180, 168, 180, 170, 178,
        182, 180, 183, 178, 182, 188, 175, 179, 183, 193, 182, 183, 177,
        185, 188, 188, 182, 185, 191],
       [ 57,  61,  57,  57,  58,  57,  61,  54,  68,  51,  49,  64,  50,
         48,  65,  52,  56,  46,  54,  49,  51,  47,  55,  55,  54,  42,
         51,  56,  55,  51,  54,  51,  60,  62,  43,  55,  56,  61,  52,
         69,  64,  46,  54,  47,  70]])

The reshaped array is now a 2darray, yet note that the original array is not changed. We can reshape an array in multiple ways, as long as the size of the reshaped array matches that of the original.

Numpy can calculate the shape (dimension) for us if we indicate the unknown dimension as -1. For example, given a 2darray `arr` of shape (3,4), arr.reshape(-1) would output a 1darray of shape (12,), while arr.reshape((-1,2)) would generate a 2darray of shape (6,2).

In [17]:
#MyTrial
san_kakeru_yon = [[12,11,10],[9,8,7],[6,5,4],[3,2,1]]
san_kakeru_yon_ndarray = np.array(san_kakeru_yon)
print(san_kakeru_yon_ndarray.size)
print(san_kakeru_yon_ndarray.shape)

12
(4, 3)


In [18]:
#ReTrial 3*4
#逆だった

re_array = [[12,11,10,9],[8,7,6,5],[4,3,2,1]]
re_array_ndarray = np.array(re_array)
print(re_array_ndarray.size)
print(re_array_ndarray.shape)

12
(3, 4)


In [22]:
#!
print(re_array_ndarray.reshape(-1))
print(re_array_ndarray.size)
print(re_array_ndarray.shape)

[12 11 10  9  8  7  6  5  4  3  2  1]
12
(3, 4)
12
(3, 4)


In [24]:
#!
#変更できないものにはできない
#️print(re_array_ndarray(-1,2)) #エラー
#もう一個サンプルのアレイを作る
re_array2 = [[13,11,10,9],[8,7,6,5],[4,3,2,1]]
re_array2_ndarray = np.array(re_array2)
print(re_array2_ndarray.size)
print(re_array2_ndarray.shape)

12
(3, 4)
[[13 11]
 [10  9]
 [ 8  7]
 [ 6  5]
 [ 4  3]
 [ 2  1]]


In [26]:
#!
#2個が6個の多次元配列をつくる
niroku = re_array2_ndarray.reshape((-1,2)) #2個ずつ切っていくイメージ
print(niroku)
print(niroku.size)
print(niroku.shape)

[[13 11]
 [10  9]
 [ 8  7]
 [ 6  5]
 [ 4  3]
 [ 2  1]]
12
(6, 2)


#Data Type

Another characteristic about numpy array is that it is **homogeneous（別名配列）**, meaning each element must be of the same data type.

For example, in heights_arr, we recorded all heights in whole numbers; thus each element is stored as an integer in the array. To check the data type, use numpy.ndarray.dtype

In [27]:
heights_arr.dtype

dtype('int64')

In [30]:
import numpy as np

heights_float = [189.0, 170, 189, 163, 183, 171, 185, 168, 173, 183, 173, 173, 175, 178, 183, 193, 178, 173, 174, 183, 183, 180, 168, 180, 170, 178, 182, 180, 183, 178, 182, 188, 175, 179, 183, 193, 182, 183, 177, 185, 188, 188, 182, 185, 191]
#189.0を189にすれば"int64"になる
heights_float_arr = np.array(heights_float)
print(heights_float_arr)
print("\n")
print(heights_float_arr.dtype)

[189. 170. 189. 163. 183. 171. 185. 168. 173. 183. 173. 173. 175. 178.
 183. 193. 178. 173. 174. 183. 183. 180. 168. 180. 170. 178. 182. 180.
 183. 178. 182. 188. 175. 179. 183. 193. 182. 183. 177. 185. 188. 188.
 182. 185. 191.]


float64


Numpy supports several data types such as int (integer), float (numeric floating point), and bool (boolean values, True and False). The number after the data type, ex. int64, represents the bitsize of the data type.